### ISSUE TITLE
Allow Cut numbers in user's Sent Exchange field

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#103]
### Description

Allow Cut Number -- Letter abbreviations for Morse numerals, such as N for 9 A for 1, T for zero, and so forth. For this bug testing the user usually uses an "N" instead of "9" in his part of the exchange in contests. 

### Steps To Reproduce

1. Type "JAY 323N" in the Exchange field. 
2. Receive error: "Invalid exchange: 'JAY 323N' - expecting '<op name> <CWOPS number>' (e.g. David 123)."

#### Expected behavior

This is what Jay actually uses for the CWOPS CWT contest. We should emulate real life exchanges. 

#### Actual Behavior

User is unable to contest the way he normally does. 

### Version information

  - Morse Runner version: 1.81
  - OS/Version: Windows 10

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Sounds good to me. When this is worked on, we will have to convert the Exchange field 2 storage type from numeric to string. This may involve a little refactoring or redesign or rework for the Exch2 field handling with the CWT Contest.
- David, @ct7aup, was the original author, so be sure to check with him if you have any questions.
- Mike has been refactoring the exchange handling protocols. I'm available if you have any questions.

**Comment by scotthibbs** [comment]
Interesting note for the one who decides to code this: In testing a pre-release for 1.82, "JAY 323N" gives the error as reported above. However, if this is ignored to run the CWT contest, the program will substitute the cut number (T or N was tested) for the number 4 instead.

**Comment by w7sst** [comment]
Hi @scotthibbs ,
I looks like this is now fixed. Can you retest this and let me know what you think. It appears to be fixed - not sure when.

[Path to 1.84-pr1](https://1drv.ms/u/s!AiN4lELeOz01q0LYuPt75uEGNMEM?e=teq7so).

Thanks,
Mike

**Comment by scotthibbs** [comment]
I tested the CWT contest with the exchange "JAY 323N" and it worked smoothly on the 1.84rc1 release. 
This is fixed and now closing.
