### ISSUE TITLE
Morse Runner on Mac

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#120]
### Discussed in https://github.com/w7sst/MorseRunner/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **scotthibbs** November 12, 2022</sup>
I've seen a few asking if there will be a Mac version. 

This may be a separate repository or beyond our capability. 

However, I wanted to pass on that this has been working on Macs prior to Catalina here: 

https://www.merzhaus.org/ham/MorseRunner/index.html</div>

**Comment by scotthibbs** [comment]
Addressed in 1.84 release
- Works on Mac systems under WINE (use Win7 bottle) or Crossover (info TNX N3RTW). 
See #291
