### ISSUE TITLE
Pre-release 1.82 Access violation Error

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#141]
### Description

![MRCE182error](https://user-images.githubusercontent.com/13142469/204197513-6870abc3-21fa-411a-989c-6aff43f024a3.PNG)

This error occurs AFTER the ARRL DX contest finishes and ARRL Field Day is selected. To reproduce, start MRCE 1.82, start ARRL DX contest for one minute. Let finish. Select ARRL Field Day and see error. 

### Steps To Reproduce

1 Click the link to download 1.82 here: https://github.com/w7sst/MorseRunner/issues/98#issuecomment-1328326003
2 This link will drop "Unconfirmed ######.crdownload" file at your computer's default location (e.g. downloads)
3 Open this file with your zip program (I suggest 7-Zip)
4 Copy the folder Morse Runner 1.82 to your desktop (or where you wish)
5 Run MorseRunner.exe by double clicking
6 Run ARRL DX contest for a one minute time limit
7 Let finish
8 Now go to contest and select ARRL Field Day
9 See error. 

#### Expected behavior

If it doesn't finish the contest this selection is without error. I'm guessing it finishes the contest but is keeping some value from the contest. Maybe switching the exchange? 

#### Actual Behavior

Error after contest finish. 

#### Reproduces how often

100% 

### Version information

  - Morse Runner version:  1.82 pre-release
  - OS/Version: Windows 10

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by scotthibbs** [comment]
Upon further testing this is any contest finish and then selecting another contest in the dropdown.

**Comment by w7sst** [comment]
I was able to reproduce it. thank you.

**Comment by scotthibbs** [comment]
Just finished testing. Works. Already closed. 

Thank you! Love it!
