### ISSUE TITLE
CWOPS CWT nonmember exchange not supported

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#143]
### Description

The exchange for CWOPS is 
Members: First Name and CWOPS member number.  
Non-members: First Name, and State/Province or DX Country prefix.
Thus, my exchange should be "Scott IN" 

### Steps To Reproduce

1. select CWOPS CWT contest
2. Input in exchange "Scott IN"
3. See error: "Invalid exchange: 'SCOTT IN' - expecting '<op name> <CWOPS number>' (e.g. DAVID 123).

#### Expected behavior

To practice a CWT without a number as in the real world. 

#### Actual Behavior

I need to fake being a member of CWOPS to play. 

#### Reproduces how often

100%
### Version information

  - Morse Runner version: 1.82 pre-release
  - OS/Version: Windows 10

### Additional context

I haven't received nonmember responses in MR... I see in the CWOPS.LIST file nonmembers but no country prefixes. 
"DK3WW,Uwe,2523,Kichendorf Germany
DK3YD,Hans,,Muenchen Germany"
so Uwe would send "Uwe 2523" and Hans would send "Hans DK" right? Does anyone in MR respond with their state if not a member? So does "KA2F,John,NJ,Eatontown NJ" send "John NJ" in MR now?

Also note: this would require the exchange labels for this contest to change from number to "#/state/prefix" 

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Internally, it looks like CWOPS CWT Contest is a so-called Dual Exchange Contest, where the second exchange is either a number or a location (state/province/dx entity). We recently introduced a new class, `TDualExchContest`, to serve as a base class for the ARRL DX Contest. It looks like we need to do the same thing for this contest.

I initially looked to see if we could do a quick change the allow Scott to send his state, but the CWT Member number is currently being carried around as a numeric value and we need support for the string. It would be easiest to handle this by deriving from the `TDualExchContest` class.

**Comment by w7sst** [comment]
Thinking about this further, I now realize that the exchange value is determined by the user's membership with CWOPS and not determined by a callsign using DXCC information. This implies that Exchange 2 for CWT Contest is either numeric or a string, thus we will need to modify the field definition to be numeric or string. Currently, the member number is stored as a numeric value (I think). We will have to use the ascii Exch2 field to support this exchange value. Also modify the behavior of `etCwopsNumber` (p/o `TExchange2Type`).

**Comment by w7sst** [comment]
Hi @scott and @Ct7aup,
I have done the following:
- updated the CWT implementation to allow non-member support for both state-side (e.g TN, IN, OR, etc), Canada (e.g. BC, ON, etc) and DX (e.g. G, SM, VP2M, etc.). 
- modified the CWOPTS.LIST file to insert missing country prefix codes (.e.g. G, SM, VP2M). This extra data will remain for the short-term since we do not have the Cty.dat file support implemented at this time (an improved DXCC lookup). The requirement (I think) is for non-US/Canada stations to use their primary country prefix (e.g. England uses 'G' for call prefixes 'G', 'M', etc.).
- removed the 'Pfx' column from the on-screen log.
- updated exchange field captions.

Here is a screen shot...
![image](https://user-images.githubusercontent.com/106113737/214469884-1327c3a5-3c76-4ce5-93ec-815610eb42dd.png)

Let me know what you think. I'll get a preliminary build out in the next couple of days.

Thanks and 73, Mike.

cc: @K6OK

**Comment by WR7Q** [comment]
Hi Mike, 
That looks good so far.  Where do I go to test the update?
Also, I notice you are not returning the entered call sign to hear on 1.82.
73,
Bob WR7Q

**Comment by w7sst** [comment]
> Also, I notice you are not returning the entered call sign to hear on 1.82.

Hi Bob, @WR7Q 
Can you explain your comment above a little more? I don't understand.
Tnx, Mike

**Comment by w7sst** [comment]
I all,
[Here is a link to download](https://nextcloud.brashlerphoto.com/s/53doidfAtcjNQgQ) the changes to support non-member CWT exchanges. This includes a modified `CWOPS.LIST` file and enhancements to MRCE. Let me know what you think. I will put this code into code review next.

73, Mike

@WR7Q @scotthibbs @ct7aup

**Comment by WR7Q** [comment]
Hi Mike,

Sorry, I have been in a CW Class.

When you put in the call sign like w1aw, you should get a response of w1aw,
I am only getting the 599 and exchange to enter.

It would probably be more effective if we could either chat on the phone or
do a zoom mtg.

73,
Bob WR7Q
CWA Admin
8018796566

**Comment by WR7Q** [comment]
Mike,

183 is still doing the same thing...

73,
Bob WR7Q
CWA Admin

**Comment by K6OK** [comment]
@WR7Q -- The official exchange in CWT is 

CQ CWT W1AW
K9DOG
K9DOG HIRAM 123
SPOT 456
TU W1AW QRZ

Are you suggesting Spot should send W1AW SPOT 456?   Some operators might do that but it's not what the rules ask for.

73 Jim K6OK

**Comment by WR7Q** [comment]
When I enter a call sign, I should hear it back like it used to and does in
1.68.  It was working...now it is not.

73,
Bob WR7Q
CWA Admin

**Comment by w7sst** [comment]
Bob,
Can you include details on which Contest you are running, what you have entered in the "Exchange" field, what mode (Pile-up vs. Single Call) you are running and a text example of what MR sends to you (what you hear) and what you are typing and expecting to type. This would help me understand better and be able to repeat it.

How are you moving between fields? Are you using "Enter" key, or tab or spacebar? Are you using function keys or other special keys (e.g. ';', etc.)?

Thank you for the extra detail. If this is a bug, we will want to create a separate issue for this.

I'll be available for a zoom call tomorrow mid-day (PST).

**Comment by WR7Q** [comment]
Hi Mike,

I am doing cq wpx, single call.  When I enter the call, I expect to hear
the call I entered...instead I am getting 599 and a nr.

Let's do a zoom call at 3pm PST?  I will send you a link.

73,
Bob WR7Q
CWA Admin
8018796566

**Comment by w7sst** [comment]
Bob, I think I found the problem. I think you have been mixing settings from an old `MorseRunner.ini` file with the new release.

Can you check your `MorseRunner.ini` file to see if you happen to have `CallsFromKeyer=1` set in the `[Station]` section? If so, please remove this line or set the value to zero. When I set this value, I can reproduce your behavior. When I set the value to `CallsFromKeyer=0`, the callsign is sent before the exchange report.

**Comment by WR7Q** [comment]
Yes, that worked.  I was being too clever and outsmarted myself.

Good fine. Thanks.

73,
Bob WR7Q
CWA Admin
