### ISSUE TITLE
MR should accept 1TT or 100 as valid power entries

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#145]
## Summary
@Yagi-Berra reported [this feedback](https://github.com/w7sst/MorseRunner/pull/138) during initial testing of ARRL DX Contest...
> re Power variations: I looked at my Cabrillo from last year's contest. I always record exactly what was sent and never convert. Program handles K, KW, 1TT, 5TT. My log also shows A00, Aoo, ATT. and NN. Program does not accept these, but should. Also non-US/VE stations should occasionally send A00, Aoo, ATT, and NN in addition to the common K, KW, 1TT, 5TT variations.

> If the home call is a USA call and I enter the power sent to me as 1TT in the lower left Power field, it automatically converts the power to 100. Some contesters agree with me and enter what was sent while others do mental conversions and enter the numerical equivalent. I think the Power field should do no conversions visible to the user. The program should accept either 1TT or 100 as valid entries.

## Motivation
As described above, contesters would like to enter what they hear.

## Detailed Description
MR should allow users to enter what they hear when recording power fields. This means when checking the log entry, the values must be converted to the equivalent numeric value and compared against the expected value.

## Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, @Yagi-Berra is available to discuss possible solutions and alternatives to this problem.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
@Yagi-Berra 
I have a solution running for you based on your description above.

Question. What about the RST field, so you want to log 5NN even though N1MM+ will prefill the field with 599?

**Comment by Yagi-Berra** [comment]
@w7sst --  In N1MM, I've never entered 599 or 5NN in any contest.  After entering the callsign I hit the spacebar and it auto-populates the RST field with 59 or 599, then skips over to the exchange field.  MRCE mimics this same behavior and is what I think most users would expect. I don't know how other contest programs like WriteLog or DXLog handle RST.

I concur with F6FVY's suggestion of being able to send ENN.  In last weekend's CQWWCW contest I heard some stations doing that.

I don't know what the other contest programs like WriteLog or DXLog do.   Anyway, my comments on "log what you hear" only applies to the exchange fields, not the RST field.
