### ISSUE TITLE
write and review announcement text.

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#164]

**Comment by scotthibbs** [comment]
Here's my very rough draft of our 1.82 announcement. Please tweak this. 

The MorseRunner Community Edition announces our newest version of this 
popular CW contest simulator. We are excited that Version 1.82 adds the Arrl DX 
contest! This addition paves the way to add even more contests for the future. In
addition, we have peaked the CWOPS CWT contest and even added cut numbers for 
sending stations. We are working on several enhancements and your feedback is needed. 
Users can send feedback at MorseRunnerCE@groups.io. Developers can join the project at
https://github.com/w7sst/MorseRunner   

additions or changes?

**Comment by scotthibbs** [comment]
Should I mention we already added the ARRL Field Day contest?

**Comment by scotthibbs** [comment]
Edit the above. 
I need to add a line for the download link... Can't believe I forgot that!

**Comment by w7sst** [comment]
Yes, we should mention ARRL Field Day. I made a few edits to your text above.

This is my initial draft. I have not yet merged this with yours above. Please feel free to start combining. I'll be back in a few hours.

ANNOUNCEMENT - Morse Runner Community Edition - v1.82.
We are pleased to announce the Morse Runner Community Edition project. We have added multi-contest support to Morse Runner, including ARRL DX, ARRL Field Day, CQ WPX, CQ WW, CWOPS CWT, and NCL NAQP contests, with more on the way. We welcome you to download this version and give it a try. At this time, N1MM-integration is not yet supported, however we hope to provide N1MM integration sometime next year.
	
To learn more, please visit us at:
- https://github.com/w7sst/MorseRunner#readme (developers/advocates area; bug reports; feature/contest requests, feedback)
- https://groups.io/g/MorseRunnerCE (our user-support area; feedback, questions, etc.)
	
To download this release, visit https://github.com/w7sst/MorseRunner/releases/tag/v1.82, scroll down to the Assets section, and download the [Morse.Runner.1.82.zip](https://github.com/w7sst/MorseRunner/releases/download/v1.82/Morse.Runner.1.82.zip) file.

**Comment by w7sst** [comment]
BTW, I'm think this text is being sent to groups where we are making an initial announcement (e.g. N1MM User Group).

**Comment by scotthibbs** [comment]
I think the directions for types of feedback and the directions to download are pretty intuitive. I tried to add some flare so that we had the 15 minimum badges to make our management happy (reference to The Office Movie), thus I added the CQ and 73 as if it were a CW QSO. Tried to write it as if discovered for the first time (that we already added several contests - made it more real etc). Also planted the idea of the user calling CQ to wet the appetite. 

The download link should work when the release is published but we can check just in case.

**Comment by scotthibbs** [comment]
Our release note should be changed to point users to the bottom of the page then right? Should we add the line from the readme on how to install on the release note? Better there than the readme really. 

I think the N1MM reference has universal appeal even for those that don't use it - it gives the idea of forward progress. But I'm happy with any of the changes you want to make.

**Comment by w7sst** [comment]
@K6OK @f6fvy @ct7aup - Scott and I have drafted text for an announcement paragraph to be sent to our respective local clubs. I'll be announcing this in the N1MM user group and a local contesting club. Please review and edit the paragraph at the top of this issue if you would like to make any changes. Or let us know if you have any suggestions for feedback. Thank you, Mike and Scott.

**Comment by w7sst** [comment]
> Our release note should be changed to point users to the bottom of the page then right? Should we add the line from the readme on how to install on the release note? Better there than the readme really.

Here, you mean the `readme.md` release note. Yes, I agree. I'll make this change before merging `readme.md`. Good catch.

> I think the N1MM reference has universal appeal even for those that don't use it - it gives the idea of forward progress. But I'm happy with any of the changes you want to make.

To the non-N1MM users, it doesn't apply. I'll add back the N1MM reference to your paragraph above.

**Comment by scotthibbs** [comment]
LOL.. I was editing it too. Yours was better than mine. lol Ok. I'm going to bed. Hopefully released soon! I'm excited.

Thank you everyone for the hard work!

**Comment by f6fvy** [comment]
If you agree, I will announce it on the french contesters list as well, hosted by our national association.

**Comment by w7sst** [comment]
> If you agree, I will announce it on the french contesters list as well, hosted by our national association.

Sounds good to me.

**Comment by w7sst** [comment]
Steve, N2IC, has asked me to **not** announce to the N1MM user group. He feels this group will immediately expect N1MM integration and will past all the good work we have done. Steve has started to work on N1MM integration. I will work with him on this.

I updated Scott's original comment at the top with my announcement plans - which are to announce to a remote radio group I use and to two local ham clubs I'm involved with.

**Comment by w7sst** [comment]
@scotthibbs @K6OK @f6fvy @ct7aup @tekenny @n2ic - I have published the 1.82 release. Feel free to copy the announce paragraph in Scott's first comment above and share with your local contacts. As I mentioned above, I will not be announcing to the N1MM groups until N1mm-MR integration is completed.

**Comment by K6OK** [comment]
@w7sst -- Just posted it, using Scott's announcement blurb, to the reflectors of the Northern California Contest Club and the Mother Lode DX and Contest Club.
