### ISSUE TITLE
CWT contest - DxStation should send 'R' after user's exchange is sent

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#175]
### Description
In the CWops CWT Contest, when the DxStation responds to user's initial callback and exchange, the 'R' (exchange received) is not sent. Instead the calling station immediately sends its exchange (Name NR). This does not follow usual operating protocol. This was noted by Bob, @WR7Q, in our discussion (see #174).

### Steps To Reproduce
1. CWT Contest
2. Start Single Calls
3. Answer the station calling by entering their callsign.
4. Observe their response does not contain an acknowledgement ('R') that they correctly copied the exchange.

#### Expected behavior
The calling station should respond with an 'R' to indicate they received my exchange.

#### Actual Behavior
The 'R' acknowledgement is missing. The station immediately starts sending their Name and Number/State/Province.

#### Reproduces how often
Always

### Version information
  - Morse Runner version: 1.82

### Additional context
In discussions with Bob, he states they teach their CWT students to not send a report until the other station acknowledges receipt of exchange with an 'R'. This is also proper contest behavior.

**Comment by WR7Q** [comment]
Hi Mike,

I may have confused you a bit.  Let me try to clear this up!!

What is currently happening in 1.82 in CWT contest:

CWT op A calls cq
B replies with B's call, name, op # (or whatever)
A replies with A's call, name, op # (or whatever)


What should happen is:

CWT op A calls cq
B replies with B's call
A replies with B's call, A's name, op # (or whatever)
B replies with B's name, op # (or whatever)

There is never an 'R' in CWT contest.

We do need the 'R' in CW WPX
after the 'correct call' is entered by B, or after the 'correct call' is
entered by B and after A sends NR? or AGN

Sorry for the confusion and I hope this helps.

73,
Bob WR7Q
CWA Admin

**Comment by w7sst** [comment]
Bob, I think you are saying you disagree with this change to add the R in the response from caller B receives the report. In other words, the original CWT implementation (I.e. version 1.82) behavior was correct.

**Comment by w7sst** [comment]
@ct7aup David, do you have an opinion on this one?

**Comment by w7sst** [comment]
It seems really odd that a contest operator would not use an R to acknowledge receipt of the prior transmission. Are you saying that in CWT contest the R is never used?

**Comment by WR7Q** [comment]
Yes, this is a different kind of contest. Some times it is used along with
other items like, '73', 'tnx Bob', etc. But I would suggest you leave it
out of MR most of the time.

You or someone may want to listen one of the Wednesdays of you have time.

73 Bob WR7Q
