### ISSUE TITLE
Dx Station's initial timeout is too long

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#180]
### Description
When copying the Dx Station's callsign, the timeout period is not recognized after many attempts at copying the callsign. In the original version 1.68, the timeout would be between 2 and 10 tries. This behavior was disabled during development of ARRL Field Day and remained in the code. This debug code should be removed and the original behavior restored.

### Steps To Reproduce

1. Start any contest using Single Calls (and perhaps Pile-Up)
2. When copying the callsign, repeated hit the F7 ('?') to request the call to be sent again.
3. You will notice after a dozen or more F7, the Dx Station is still trying to send the call.

#### Expected behavior
After a reasonable number of times resending their callsign, the DX Station will eventually move on since I was unable to copy their callsign.

#### Actual Behavior
This timeout occurs after ~100 attempts.

#### Reproduces how often
100%

### Version information
  - Morse Runner version: 1.80+

### Additional context
As mentioned earlier, this was debug code that was unfortunately not removed from the code. Sorry about that.

**Comment by w7sst** [comment]
I suppose one could argue that if I'm learning, I would want extra time to copy the callsign correctly. However, in a real contest, the other station may not wait that long. What we need is the ability for the sender to QRS (slow down) if the user is having a hard time copying the station.

**Comment by WR7Q** [comment]
I would leave it be.  No need for QRS...

73,
Bob WR7Q
CWA Admin
