### ISSUE TITLE
Add support for JARL Major Contests

### ISSUE THREAD

**Issue by jr8ppg** [w7sst/MorseRunner#187]
## Contest information

* **Contest Name:** ALL JA contest, All Cities All Guns(Countries) contest (ACAG)
* **Contest Rules:** https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/all_ja/all_ja_rule.htm (japanese only)
* **Call History file name:** DIC_ALLJA.TXT, DIC_ACAG.TXT

### Unique contest behaviors

* ALL JA contest use prefecture codes  for exchange number.
* ACAG contest use city/gun(country) codes for exchange number.
* In the JARL contest, a code that means power is added to the end of the exchange number.
P is 5W oe less(QRP), L is 10W or less, M is 100W or less, H is greater than 100W.
* Most of the rules of other contests held in Japan follow the rules of the ALLJA contest.

ALLJA examples
* For 100W station in Tokyo
599 10M
* For 1KW station in Hokkaido Ishikari branch office 
599 106H

ACAG examples
* For 100W station in Hachioji City, Tokyo
599 1002M
* For 1KW station in Chuo Ward, Sapporo City, Hokkaido
599 010101H

### Additional information

*

### Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to discuss questions or alternatives regarding the implementation of this contest.
- [ ] Yes, I'd like to review and provide feedback on the proposed solution.
- [ ] Yes, I'm available to help test this contest. Let me know when it is ready for early testing.

**Comment by w7sst** [comment]
Hi @jr8ppg ,
Congrats on your progress with the JARL Contests.

How can I help? Are you still making changes to this code? Please create a Pull Request when you are ready to start the code review. If you need help, let me know and I can create it for you. After the code review, I will merge the Pull Request.

Also, I noticed a memory leak in both of your new contests in the LoadCallHistory procedures. In the loop that is adding each CallRecord, if a continue message is executed, the object created by CallRecord.Create is lost. You can see the fix in the CWSST.pas file. Let me know if you want help with this and I can make the changes and merge back into your branch.

**Comment by jr8ppg** [comment]
Hi @w7sst 

Thanks for your support.
I fixed the memory leak.
I will create a pull request so please review it.
