### ISSUE TITLE
My exchange number is also randomly abbreviated

### ISSUE THREAD

**Issue by jr8ppg** [w7sst/MorseRunner#205]
### Description

My exchange number is also randomly abbreviated.
If the exchange type is etSerialNr, etCqZone, etItuZone, etAge, etPower, it is abbreviated by a random number.
I think my exchange number should be in a fixed format.

I am asking for your opinion please.

### Steps To Reproduce

1. 
2. 
3. 

### Version information

  - Morse Runner version: [e.g. 1.68]
  - OS/Version: [e.g. Windows 10]

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by jr8ppg** [comment]
How about this as a revised proposal?
https://github.com/w7sst/MorseRunner/commit/bf101ea93e5984a7d08bd2f90678279ba9b66de8

**Comment by w7sst** [comment]
Hi,
Yes, I agree with your proposal if my station having a fixed exchange value. Good idea. This behavior matches real contests. 

Thank you and best regards. 

Mike W7SST

**Comment by w7sst** [comment]
Perhaps we missed the use case. In a contest, the user will want to send abbreviated numeric exchange fields. Your original concern was the random behavior. The fix turned off abbreviated fields. What we wanted to disable was the random behavior for the user's station only.

I'm going to reopen this issue. I'll submit an alternate solution that will remove the random behavior for the user's station. In other words, the user's station will always send abbreviated calls.

**Comment by jr8ppg** [comment]
In contests that use serial numbers, such as WPX contests, many stations will send the replacement number in abbreviated.
Exchange numbers will either always be abbreviated or always full.

This fix code is always full.
https://github.com/w7sst/MorseRunner/commit/bf101ea93e5984a7d08bd2f90678279ba9b66de8

**Comment by jr8ppg** [comment]
@w7sst 
Hi Mike san
This is the revised code proposal.
https://github.com/w7sst/MorseRunner/commit/c8f691a52b0779e7bc52187dfec4966058baa050
Thank you, Taka

**Comment by w7sst** [comment]
@jr8ppg 
Taka,
I uploaded a few additional changes, including some test code for cut numbers. Once we are satisfied, I can merge mainline into your branch and we can integrate. You can give it a try and work through the merge issues if you want, but I'll be happy to do it. Thank you again for your contributions. 

Thank you, Mike

**Comment by jr8ppg** [comment]
@w7sst 
Hi Mike san,
I have commented here, please refer to it.
https://github.com/w7sst/MorseRunner/commit/cfd7fc340dd511a2f2531c3888360b78730c9dc4#r138573464
Thank you, Taka

**Comment by w7sst** [comment]
@jr8ppg 
Hi Taka, do you have time to download and verify this fix using [v1.84-rc1](https://1drv.ms/u/s!AiN4lELeOz01q1bYfmH8YVW2-9KH?e=XWyb7J)?

Thank you, Mike

**Comment by jr8ppg** [comment]
@w7sst 
Hi Mike san,
I'll test it tonight.
Thank you, Taka

**Comment by jr8ppg** [comment]
The test result was OK.

CQWW
always abbreviate
my 599 9 -> 5NN N
my 599 10 -> 5NN 1T
ok

CQWPX
randomly abbreviate
dx 599 009 -> 5NN T T N
dx 599 010 -> 5NN T 1 T
dx 599 010 -> 5NN O 1 O
ok

JARL ALLJA
dx 599 10M -> 5NN 1 T M
dx 599 10H -> 5NN 1 O H
dx 599 09H -> 5NN 1 N M
ok
