### ISSUE TITLE
Contest Parser Reading First Line of File

### ISSUE THREAD

**Issue by Stingy49** [w7sst/MorseRunner#210]
### Description
Running CWT I got the call "ORDER" with name "CALL" and exchange "NAME". Looking at CWOPS.list these are only present in the first line of the file.

![image](https://github.com/w7sst/MorseRunner/assets/26490248/c19d5560-bb9d-48ec-b530-3cae41474b04)

### Steps To Reproduce
1. Run CWOPS CWT
2. Get lucky? (or delete all lines in CWOPS.list after 11)

#### Expected behavior
First line of call file shouldn't be valid to pull 

#### Actual Behavior
First line of call file is used as a potential caller.

#### Reproduces how often
Extremely rare. System has to select the first line out of possible thousands.

### Version information
1.83, Windows 7

### Additional context
Can be reproduced by deleting all lines in the CWOPS.list file after line 11. (So that one normal call is kept, not sure if one normal call is needed or not)

### Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi @Stingy49 ,

We are trying to wrap up the 1.83.1 bug fix release. 
Will you have some time over the next few weeks to try testing the fix to your reported issue?

1) [Here](https://drive.google.com/file/d/1BOwCaAuACwKt1jVOzGEZMOOGZqxhcmrt/view?usp=sharing) is a link to the pre-release build.
1) When complete, please add a comment to this issue describing your testing and results.
1) Add the `verified` label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by w7sst** [comment]
If you are unable to change labels or assign this issue to Scott, please mention @scotthibbs or @w7sst in your testing comment and we will update the issue for you. Not all users have permissions for changing the label fields. Thank you for your help - we appreciate it.

**Comment by Stingy49** [comment]
Tested by deleting all lines in CWOPS.LIST after line 11. No stations called back. This is the correct behavior. Restored file to normal and station would call back. This is also the correct behavior. Issue seems fixed.
