### ISSUE TITLE
RIT - Normal / Reversed

### ISSUE THREAD

**Issue by Mark-K5GQ** [w7sst/MorseRunner#211]
## Summary

Add in Setting "RIT  Normal / Reversed"  
Normal -  depressing the "UP" arrow key makes the audio pitch of the calling station go lower. (With the "down" arrow key making the pitch go up.)
Reversed - depressing the "UP" arrow key makes the audio pitch of the calling station go higher. (With the "down" arrow key making the pitch go lower.)
 
## Motivation

    N1MM  logging program - the "UP" arrow makes the pitch go up.   This selection would allow the user to choose which direction the "UP" / "DN" arrow key moves the pitch.  

## Detailed Description
   New Settings " RIT"
  Selection is "Normal / Reversed"
  Reversed is selected.  
  the "UP" arrow NOW makes the pitch go up. The "DN" arrow makes the pitch go lower.

## Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to discuss possible solutions and alternatives to this problem.
- [X ] Yes, I'd like to review and provide feedback on the proposed solution.
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by scotthibbs** [comment]
This is addressed and fixed in the 1.84 release. See issue #253 which impliments the RitStepIncr=50 setting in the ini file. This can also be set to a negative value.
