### ISSUE TITLE
CQ WPX;  0 is not a valid entry for the serial number

### ISSUE THREAD

**Issue by Mark-K5GQ** [w7sst/MorseRunner#213]
### Description
Received "T T" for the serial number.  Entered "0"  
Attachment shows line 1 received 599 0000 
I believe "0" is not a valid serial number entry in any contest. Numbers start with 1.

### Steps To Reproduce

Contest  -  CQ WPX
NR digits is set to 2.  I have not tried other setting of NR
RUN - Single calls 
Run = 7 minutes ;  usually occurs within the first 2 minutes.

1. 
2. 
3. 

#### Expected behavior

Serial number "0" not sent. 

#### Actual Behavior

Received "T T" for the serial number.  Entered "0"  
#### Reproduces how often

It takes usually more than 4 times before "0" occurs  as a sent serial number.
### Version information

1.83 version - Windows 10
  - Morse Runner version: [e.g. 1.68]
  - OS/Version: [e.g. Windows 10]

### Additional context

Previous version Morse Runner does not have "0" sent as serial number.

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi Mark,
Good find. This will be easy to fix. The random number generates a zero and we are not adding 1 to this value. 

Thanks and 73,
Mike W7SST

**Comment by Mark-K5GQ** [comment]
Mike,
Great!I wondered how the random number generator worked down to the detail..  
Mark    On Monday, June 12, 2023 at 12:22:48 AM CDT, Mike Brashler ***@***.***> wrote:  
 
 


Hi Mark,
Good find. This will be easy to fix. The random number generates a zero and we are not adding 1 to this value.

Thanks and 73,
Mike W7SST

**Comment by w7sst** [comment]
Hi @Mark-K5GQ ,

We are trying to wrap up the 1.83.1 bug fix release. 
Will you have some time over the next few weeks to try testing the fix to your reported issue?

1) [Here](https://drive.google.com/file/d/1BOwCaAuACwKt1jVOzGEZMOOGZqxhcmrt/view?usp=sharing) is a link to the pre-release build.
1) When complete, please add a comment to this issue describing your testing and results.
1) Add the `verified` label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by w7sst** [comment]
If you are unable to change labels or assign this issue to Scott, please mention @scotthibbs or @w7sst in your testing comment and we will update the issue for you. Not all users have permissions for changing the label fields. Thank you for your help - we appreciate it.

**Comment by scotthibbs** [comment]
This was fixed. I did not receive a zero serial..
