### ISSUE TITLE
CW message for CQ WPX contest has multiple tones

### ISSUE THREAD

**Issue by RhinoLance** [w7sst/MorseRunner#214]
### Description
When using the "QC WPX" contest, the transmitted CQ message is as follows:
`CQ <MYCALL> TEST`

The "TEST" part of the message is transmitted at a different tone to the proceeding characters.  Sometimes the tone is higher, and sometimes lower.

Why is this an issue?  After a while, I tune out my own CQ message, waiting for responses.  With the change in tone, it sounds like a station is calling and I start recording "TE" then realise it's still the CQ message.  Now I have to clear the field before the actual callers begin.

### Steps To Reproduce

1. Select the "CQ WPX" contest in the "Contest" dropdown.
2. Click the "Run" button.
3. Trigger a CQ call by either pressing <ENTER> from the Call box, or pressing F1.

#### Expected behavior
The following CQ call should be sent at the same tone:
`CQ <MYCALL> TEST`

#### Actual Behavior
"CQ <MYCALL>" is sent at one tone, and "TEST" is sent at a slightly different tone, sometimes higher, and sometimes lower.

#### Reproduces how often
Every CQ call.

### Version information
  - Morse Runner version: 1.83
  - OS/Version: Windows 11

### Additional context
The same behaviour appears to be exhibited in the "CQ WW" contest too, thought have not tested thoroughly.

### Can you help?
-  Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi Lance,

Interesting. Can you try setting your callsign to something like K7TEST and try your test again. I do not have computer access right now, but would be interested in the result. You might also enable the record option on one of the menus to save a recording of your test. 

Thanks and 73,
Mike W7SST

**Comment by RhinoLance** [comment]
Thanks for your response Mike,

I wasn't aware of the recording feature, so made a recording and did some frequency analysis with Audacity.  It shows no change in tone at all.  😕

Following a lot of head scratching and testing, I'm sure I can still hear a change, but every time I make a new recording, the spectrum analysis shows only one frequency is being sent.  Therefore at this stage it appears the bug exists somewhere between my ears and brain.

I'll close this issue as "in my head", but if I find some objective evidence to the contrary, I'll re-open it (or log a new issue).

Sorry for the apparent false alarm.

Lance, VK7ZA
