### ISSUE TITLE
NAQP Does Not Accept Numbers in State Field

### ISSUE THREAD

**Issue by Stingy49** [w7sst/MorseRunner#216]
### Description
North American QSO Party Contest does not accept numbers in the state field which is needed to properly enter some location such as KP4.

### Steps To Reproduce
1. Start contest
2. Try to enter a number in the State field

#### Expected behavior
Numbers should be allowed.

#### Actual Behavior
Numbers are not allowed.

#### Reproduces how often
100%

### Version information
1.83

### Additional context
4U1/u 6Y 8P C6 CM CY9 CY0
HK0 J3 J6 J7 J8 KG4
KP1 KP2 KP4 KP5 PJ5 PJ7
TI9 V2 V3 V4 VP2E
VP2M VP2V VP5 VP9 XE XF4
YN YS YV0

Are the acceptable locations containing numbers listed as examples in [https://ncjweb.com/NAQP-Paper-Log-Form.pdf](https://ncjweb.com/NAQP-Paper-Log-Form.pdf) the [rules](https://ncjweb.com/NAQP-Rules.pdf) also mention it (Section 11).

### Can you help?
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi @Stingy49, I have a question...

From what I understand about the NAQP Contest, non-North American (NA) stations send only their name as the exchange. NA stations send both name and location whereas non-NA send only their name.

Do you see this during the NAQP Contest? I have not participated in the NAQP contest for several years now and forget what the typical exchange is for a non-NA station. According to the rules, they only send their name.

I also notice that when working a non-NA station, N1MM automatically fills the third exchange field with the dx station's prefix. This leads me to believe that the dx station is only sending their name.

What have you seen during a contest?

Thank you for your help. 

73, Mike

**Comment by w7sst** [comment]
@Stingy49 Update: I also see that N1MM will automatically enter 'DX' into the log when the State field is left empty. This seems like a reasonable thing to do. I think I'll simply allow the user to enter an empty State exchange field and log 'DX' whenever this location field is empty.

I will also try to allow a non-NA station to send only their name.

**Comment by Stingy49** [comment]
Hey Mike,

Thanks for getting to this!

The prefixes I listed in Additional Context are actually considered North American stations per NAQP rules and NOT DX. So they do send their location like any other state or province, and it needs to be logged. For example, KP2 for a US Virgin Islands station, which morse runner currently wont accept in the state field because of the 2.

It's an edge case I should have explained better in the original bug submission. If you read section 11 of the rules I linked, it talks about this "...and other North American entities as defined by the ARRL DXCC List. For other North American entities, please use the standard DXCC prefix for the country in the received location field in your log. See multiplier list included with sample paper logs.".

I agree non-NA stations do only send their names. I also like your change to auto populate DX! Less typing :).

Thanks for this great software!

73,
-Derek

**Comment by w7sst** [comment]
Hi @Stingy49,
Well, this NAQP certainly needed a lot of work. I will get a pre-release build available soon so you can try it out.

Here are my checkin notes:
>
>    NAQP - fix KH6/KL7 and other NA/Non-NA behaviors
>    
>    - allow KH6/KL7 to be used as the user's exchange
>    - non-NA stations send Name only (no location)
>    - when working a non-NA station, an empty State field is logged as DX
>    - allow '/' in State/Prov/Entity field
>    - when user is a non-NA station, only NA stations are worked
>    - only NA State/Prov/Entity (including Hawaii) are valid multipliers

**Comment by w7sst** [comment]
Hi @Stingy49 ,

We are trying to wrap up the 1.83.1 bug fix release. 
Will you have some time over the next few weeks to try testing the fix to your reported issue?

1) [Here](https://drive.google.com/file/d/1BOwCaAuACwKt1jVOzGEZMOOGZqxhcmrt/view?usp=sharing) is a link to the pre-release build.
1) When complete, please add a comment to this issue describing your testing and results.
1) Add the `verified` label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by w7sst** [comment]
If you are unable to change labels or assign this issue to Scott, please mention @scotthibbs or @w7sst in your testing comment and we will update the issue for you. Not all users have permissions for changing the label fields. Thank you for your help - we appreciate it.

**Comment by Stingy49** [comment]
I’ll be able to test the update this weekend or early next week.

-Derek Eells

**Comment by Stingy49** [comment]
Happy to help! Thanks for improving this great practice software.

-Derek Eells
