### ISSUE TITLE
ARRL DX format for KH6/KL7 is incorrect

### ISSUE THREAD

**Issue by nh6o** [w7sst/MorseRunner#218]
I just discovered MRCE 1.83, and was testing the ARRL DX contest setup with my Hawaii callsign. I entered my exchange as a power level, since Alaska/Hawaii entrants are considered DX, and received an "invalid exchange" error. Can this be easily corrected in a future update?

_Originally posted by @nh6o in https://github.com/w7sst/MorseRunner/discussions/217_

**Comment by w7sst** [comment]
Yes, this can be easily fixed. Thank you for the feedback. I will get to this once I have access to my computer again. 73, Mike

**Comment by w7sst** [comment]
Hi @nh6o,

We are trying to wrap up the 1.83.1 bug fix release. 
Will you have some time over the next few weeks to try testing the fix to your reported issue?

1) [Here](https://drive.google.com/file/d/1BOwCaAuACwKt1jVOzGEZMOOGZqxhcmrt/view?usp=sharing) is a link to the pre-release build.
1) When complete, please add a comment to this issue describing your testing and results.
1) Add the `verified` label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by nh6o** [comment]
Thanks, Mike. I’ll try it out tonight!73, Bob NH6OOn Feb 1, 2024, at 5:37 PM, Mike Brashler ***@***.***> wrote:﻿
Hi @nh6o,
We are trying to wrap up the 1.83.1 bug fix release.
Will you have some time over the next few weeks to try testing the fix to your reported issue?

Here is a link to the pre-release build.
When complete, please add a comment to this issue describing your testing and results.
Add the verified label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by nh6o** [comment]
A test ARRL DX using my call worked perfectly for me. I tried entering a bunch of AK/HI/PR/AS/VI sample calls to make sure they were recognized as DX, and all worked as expected.
I don't appear to have the privilege to add a label or assign a task - thanks for giving me the chance to test the edited code.
Bob NH6O

**Comment by w7sst** [comment]
NH6O's testing feedback...
>A test ARRL DX using my call worked perfectly for me. I tried entering a bunch of AK/HI/PR/AS/VI sample calls to make sure they were recognized as DX, and all worked as expected.
>I don't appear to have the privilege to add a label or assign a task - thanks for giving me the chance to test the edited code.
Bob NH6O

Marking as verified. I'll let @scotthibbs close this after working with release notes.
