### ISSUE TITLE
WPM keyboard entry incorrect behavior for Spin Box (up down control)

### ISSUE THREAD

**Issue by cwhelchel** [w7sst/MorseRunner#219]
### Description
Keyboard entry into the CW Speed text box doesn't allow direct entry of CW speed via typing.

### Steps To Reproduce
Use keyboard to enter numerical value into CW Speed WPM spin control.
(do NOT use up down buttons)

#### Expected behavior
Allow direct numerical entry 

#### Actual Behavior
number changes to either 110 or 120 wpm and allows no further input or deletion

#### Reproduces how often
every time

### Version information

  - Morse Runner version: 1.83
  - OS/Version: Windows 10

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
@cwhelchel, I found the problem in the code. This bug was introduced during some early refactoring. I will include this in the upcoming v1.83.1 bug fix release.

**Comment by w7sst** [comment]
Hi @cwhelchel, I was wondering if you could describe your usage of typing directly into the WPM spin control. I remember watching some YouTube videos years ago showing HST operators increasing the sending speed during each of their transmissions to increase their run rates. I was curious how you navigate to this control in 1.68 (original versions) before using 1.83. Do you use a tab key? do you use the mouse and click, the hit backspace? Do you select the current speed characters using the mouse and type to replace the selection? Do you enter the control, use Cntl-A to select all and then type? You get the idea. I was just curious how you handle the navigation to and from this control. Also curious why you use it.

Thank you, Mike

**Comment by cwhelchel** [comment]
@w7sst  hi mike. Let me pull down the latest and check it out. Off the top of my head, for the 1.68 version I would just click on the control to gain its focus (it would auto-select all the text upon gaining focus), type any number, and it would go wonky. Then I'd have to use the up down buttons to fix it. (Again from memory here)

Normally I would expect the controls to take numeric keyboard input and update on focus lost (via tab or clicking away) but also accept a press of the Enter key. As far as use in morse runner, it was quicker for me to type in my desired practice WPM than mouse clicking up and down. Because I may want to do large swings like say practice real slow at 15 then put in 30.

As far as what contesting OPs may do, I cant fully say. But, notably, N1MM+ allows the WPM to be changed at anytime via Page Up and Page Down. I've noticed that Log4om's cw keyer interface copies this behavior as well.

**Comment by w7sst** [comment]
Hi @cwhelchel, I have told myself many times to always read the manual. I have been using MR for several years and did not know that the current implementation, 1.83, support PgUp and PgDwn keys to increment/decrement MR's CW sending speed. I did not know this. So I looked in the code and there it is. The readme file also documents this:
>PgUp/PgDn, Ctrl-F10/Ctrl-F9, Alt-F10/Alt-F9 - keying speed,
>in 5 WPM increments.

I will fix your reported behavior of direct keyboard entry of numeric digits into the speed control. This is clearly wrong and a change from 1.68 behavior.

Other observations...
- I notice that if I double click in the CW speed control, the digits are selected. If I single click into the control, the cursor is placed but not auto-selected. After placing cursor, you can hit Cntl-A to select all digits and then type. This is different than you remember as you thought an auto-select occurred upon simple entry. I will download 1.68 and see what the behavior in the original version. We want to at least match the original behavior.
- I also agree that the Enter key could be improved. The enter key will send the next MR action (CQ for example if not in the middle of a QSO), but the current focus does not change. It would be nice if the focus moved to one of the QSO entry boxes.
- Same thing with the spacebar. If focus is in the CW speed control and you finish typing, it would be nice if hitting the spacebar would move you to the next Exchange entry field (callsign, exch1 or exch2, depending on QSO state).

For the scope of this bug report, I will restore the ability to type directly in the CW Speed control. The user will have to manual move focus back to the exchange area. Oh, I did notice that TAB will move you back to the first exchange entry field. Perhaps the spacebar should do the same.

Thank you for your comments and feedback. We appreciate it.

**Comment by w7sst** [comment]
Hi @cwhelchel  ,

We are trying to wrap up the 1.83.1 bug fix release. 
Will you have some time over the next few weeks to try testing the fix to your reported issue?

1) [Here](https://drive.google.com/file/d/1BOwCaAuACwKt1jVOzGEZMOOGZqxhcmrt/view?usp=sharing) is a link to the pre-release build.
1) When complete, please add a comment to this issue describing your testing and results.
1) Add the `verified` label and assign the issue to @scotthibbs. Scott will review, update release notes, and close this issue.

Thank you,
Mike

**Comment by w7sst** [comment]
If you are unable to change labels or assign this issue to Scott, please mention @scotthibbs or @w7sst in your testing comment and we will update the issue for you. Not all users have permissions for changing the label fields. Thank you for your help - we appreciate it.

**Comment by cwhelchel** [comment]
@scotthibbs @w7sst yeah looks like I can't assign labels. I did download the preview release and it is behaving as expected.

**Comment by w7sst** [comment]
One last change... move the keyword into the `[Settings]` section of the `MorseRunner.ini` file.

**Comment by w7sst** [comment]
Here is the Readme.txt file entry:
```
  PgUp/PgDn, Ctrl-F10/Ctrl-F9, Alt-F10/Alt-F9 - keying speed,
    in 2 WPM increments. HST Competition uses 5 WPM increments.
    The default WPM Step rate is 2. Valid values range between 1 and 20.
    You can override this value by changing the WpmStepRate entry in the
    MorseRunner.ini file, e.g.:
            [Settings]
            WpmStepRate=2
```
