### ISSUE TITLE
Usability - Hide Dx Station's Entity status string if same as user's Entity

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#222]
### Description
It is not necessary to display the DxStation's Continent/Entity information when it matches the current user's Continent/Entity information. This occurs when the contest's history file does not contain the optional user text fields. For example, for a US station running a contest, when they work a US station and the call history file does not contain a user text field, the string '<call> - NA/United States of America'. In this case, the user has already recognized the callsign as a domestic call and the information in the status bar is not helpful nor interesting.

### Steps To Reproduce
1. Pick a contest (not K1USN SST)
2. Set a US callsign for the current user
3. Start Single Call mode
4. work a few stations until you see 'NA/United States of America'

#### Expected behavior
I think it would be more interesting for the simulation to show Continent/Entity information for those callsigns that are not in the user's current Entity. Users will recognize callsigns from their current Entity.

#### Actual Behavior
Currently, when the callsign record from the history file does not contain a user text field, the DxStation's Continent/Entity is displayed.

#### Reproduces how often
Always.

### Version information
  - Morse Runner version: 1.83
  - OS/Version: Windows 10

### Additional context
- This cannot be reproduced with SST Contest due to an existing bug (#208).

### Can you help?
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Do you want to give this one a try?

**Comment by scotthibbs** [comment]
I'm not sure what I'm looking for here. I ran several contests and I'm still getting the NA/United States of America (below the log window) if I use my KD4SIR when I receive a domestic call. Please advise.

**Comment by w7sst** [comment]
I think this was for the K1USN SST contest only. Sorry for the confusion and for my lack of detail in the notes.

**Comment by scotthibbs** [comment]
NP. I just ran the contest and I'm seeing the city and state of the responder. I'm not seeing NA or USA. I'm guessing that was as expected. Sorry I haven't been working this contest much.
