### ISSUE TITLE
All Contests - Spacebar and Tab should auto-select both exchange fields

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#227]
## Summary
The spacebar and tab keys should auto select the exchange field as the user navigates between fields.

## Motivation
Improve usability by having consistent behavior on both exchange fields. This also matches current N1MM behavior using the spacebar and tab fields. 

## Detailed Description
Currently, the spacebar will move between the callsign and the two exchange fields. The middle field (e.g. RST) is selected with the spacebar, but the last field is not selected. This change will provide auto select for both exchange fields. The first field behavior will not change.

## Additional context
This change will match N1MM behavior.

## Tasks

**Comment by w7sst** [comment]
Scott, do you want to give this one a try?

**Comment by scotthibbs** [comment]
As noted in the readme, the Tab key does more than the exchange fields. The space bar just goes between all the exchanges.

**Comment by scotthibbs** [comment]
I take that back, both tab and space remained in the exchanges during a contest.
