### ISSUE TITLE
Bandwidth adjustment using Cntl-key with mouse wheel

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#252]
## Summary
Adds ability to adjust receive bandwidth using the Control-key along with mouse wheel movement.

## Motivation
Ease of use. Allows both RIT and Bandwidth to be adjusted using mouse wheel.

## Detailed Description
- Bandwidth is increased when pressing Control-key and rotating mouse wheel forward (away from user).
- Bandwidth is decreased when pressing Control-key and rotating mouse wheel backward (towards the user). 

## Additional context
- integrates prior work from @f6fvy and others.
- Several other forks have previously included this change. Our fork is catching up.

## Tasks

**Comment by scotthibbs** [comment]
@w7sst I verified this worked as described with 1.83rc1.
