### ISSUE TITLE
No RIT needed for Single Call Modes

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#257]
## Summary

It was suggested by Bob WR7Q that the single call modes should not need to use RIT. This seems to be reasonable and within the scope of what the single call mode is used for. 

## Motivation

This seems to be reasonable and within the scope of what the single call mode is used for. 

## Detailed Description

In the single call mode of a contest, having each responder on frequency makes sense. Thus in a timed setting having to use RIT in 
this mode seems to distract from the actual results desired.

## Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to discuss possible solutions and alternatives to this problem.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
I agree. this would be easy to implement. I would reduce the random offset generated for a remove station (currently +/- 300Hz). I would probably set this to +/-100Hz for Single Call mode, perhaps a little smaller.

Should we try to include this for 1.84?

@scotthibbs @WR7Q @K6OK @f6fvy

**Comment by WR7Q** [comment]
I agree. Take it out. Mostly just an annoyance.

73,
Bob WR7Q
CWA Admin
