### ISSUE TITLE
Improve Run button with default Run Mode and Stop icon

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#281]
## Summary
Add the notion of a default run mode under the existing Run button. User can start a contest using the Run button's dropdown list and then subsequently press the Run button to start the selected Run mode. The default Run Mode will be rendered in bold font. Once started, the Run button is renamed to "Stop" along with a red icon. Pressing the red Stop button will stop the simulation.

## Motivation
Useability. Currently the user has to either use the Run menu of click on the Run button's dropdown list to start Single Call mode. Currently only Pile-Up can be started by pushing the Run button. This change makes it easier to start/stop a favorite mode (e.g. Single Calls).

## Detailed Description
1. User can start a contest using the Run button's dropdown list.
2. This default Run Mode will be identified using a bold font in the dropdown list.
3. The default run mode will be retained in the `MorseRunner.ini` file across MR invocations.
4. Subsequent pushes of the Run button will start the selected Run mode.
5. Once started, the Run button will be renamed to "Stop" along with a red Stop icon.
7. When user pushes the red Stop icon, simulation will stop and the button will be renamed to "Run" along with its green Start icon.

Here is a picture showing the default Run Mode for __Single Calls__...
![image](https://github.com/w7sst/MorseRunner/assets/106113737/3c6d51d3-3c8a-4a6c-b7b6-ff3c488fe915)

Here is a picture showing the new Stop button during a running simulation...
![image](https://github.com/w7sst/MorseRunner/assets/106113737/c690a677-5909-425d-bc9c-1192d96a177a)

And finally, after simulation is stopped, the start/stop button is renamed back to "Run"...
![image](https://github.com/w7sst/MorseRunner/assets/106113737/6040e7e0-0c3f-4c96-99e4-79d71f1edbc5)

## Additional context
Additional notes
- The Run menu will not be affected by this change, meaning the default run mode is not identified in Bold font. This can change in the future.

**Comment by w7sst** [comment]
@scotthibbs @K6OK @f6fvy @WR7Q @jr8ppg 

Hi all,
I'm guilty of what is called feature creep when we are close to a release. I've been playing with adding a default Run Mode to the start/stop button and finally came up with this. I think it works pretty well.

Do any of you see any reasons why this should not be included in 1.84? I'll get a build available soon so you can give it a try. Let me know what you think.

**Comment by WR7Q** [comment]
I like it!

**Comment by scotthibbs** [comment]
Just changing it to stop while running is issue #96 

The whole run button function needs a complete revamp which can be this issue but it really needs to be broken down separately and decided upon. For example, the duration should be before the run button in the gui, not after. This avoids the user hitting run before they had a choice to select for how long. Even if you remember to set your duration on the right, you gotta go "back" left to select run. That's just one issue. 

My suggestion is getting rid of the run's drop down entirely is discussed elsewhere.

**Comment by scotthibbs** [comment]
Run button with stop works. I will close this issue and #96
