### ISSUE TITLE
Response is slightly too fast

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#283]
### Description

Bob WR7Q has noted that the responders are slightly too fast during the QSO. If the user does not send a response right away the responder doesn't wait long enough. Usually we need a second or so to finish typing. I've noticed this too where I just get ready to send "TU" and have had to wait for them to get done repeating themselves. I attributed this to my lack of morsey skilz, but it appears Bob has experienced this too. 

### Steps To Reproduce

1.  Start a contest (tested with FD and WPX)
2. Send someone's call and wait
3. Notice that they seem impatient to let you type

#### Expected behavior

Bob notes this seems a little faster than 1.68. We need to add a second or two before a non-response is triggered for the responder. 

#### Actual Behavior

The responder seems impatient to let the person type or write in the log. 

#### Reproduces how often

I'm not sure if this is all the time, maybe some are quicker than others. 

### Version information

  - Morse Runner version: [e.g. 1.68] 1.83
  - OS/Version: [e.g. Windows 10] win11

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by keptenkurk** [comment]
Note that you can hit "Enter" to start your response and finish entering/correcting the callsign while responding. I love these impatient callers which mimics real contests perfectly. - PA3DSB

**Comment by f6fvy** [comment]
Fully agree with PA3DSB. The users must learn how to "type ahead".

**Comment by scotthibbs** [comment]
I was wanting to fix the responder not waiting long enough to hit enter, just pausing slightly and resending again their exchange. However, @keptenkurk is right, "I love these impatient callers which mimics real contests perfectly. - PA3DSB" There are those who are impatient and would do this in real life. Closing the issue.
