### ISSUE TITLE
ARRL FD - call history distribution has too many home/portable stations

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#286]
### Description
In 2020, the Covid pandemic caused ARRL FD Rule changes that allowed home stations to be used and the score could be contributed to their clubs score. This resulted in a large growth in home stations. For MRCE, this creates a problem in that the simulation now has a high-number of home/portable stations that may be associated with a club. We want to reduce the number of home/portable stations associated with a club.

### Steps To Reproduce
See steps in Issue #285 .

#### Expected behavior
The distribution of club classifications should match reported results. This provides a more realistic simulation experience and preparation for FD operations.

#### Actual Behavior
User observes a high number of home/portable stations. See #285 for additional details.

#### Reproduces how often
100%

### Version information
  - Morse Runner version: v1.83, v1.84-rc3
  - OS/Version: [e.g. Windows 10]

### Additional context
- Please see additional discussion in the original Issue #285.
- For now, this Issue will remove home/portable stations with a club name in the `UserText` field of the call history file.
- After v1.84, Issue #285 will be revisited again to implement a better algorithm that tracks all club names and eliminates any home/portable stations associated with a club operation. The club operation is typically a class A, C, or F.
 
### Can you help?
- [x] Yes, @scotthibbs said he was available to help test a solution to this problem.

**Comment by w7sst** [comment]
I decided to reimplement the solution for this. When running, it was bothering me that all the 1B and 1D stations did not have any club names. This is not true, as many clubs may be entered as only a single portable or single home station. We are wanting to filter out the home/portable stations that share the same club name as the main club station (e.g. 3A).

**Comment by scotthibbs** [comment]
I thought 1D with club names was a bug but once it was pointed out that Covid rules allowed people to operate from home for a club, I was happy. I simply forgot this. This can be changed or not depending on your preference.

**Comment by w7sst** [comment]
> I thought 1D with club names was a bug but once it was pointed out that Covid rules allowed people to operate from home for a club, I was happy. I simply forgot this. This can be changed or not depending on your preference.

The problem occurs when a 1D with club name also occurs with a 3A station with the same club name. In this case, we want to remove any portable/home stations with the same club name. What we want to keep are any 1D stations with a club name with not other occurrences of that club name - meaning, the club operated a single station as either portable or home.

**Comment by w7sst** [comment]
I have finished my rework of this. This new solution eliminates all home/portable stations that are associated with a club and keeps 25% of all home/portable stations that are not associated with a club. Keeping 25% of these gives a good distribution without feeling like home/portable (1D/1E) stations are dominating the contest. During FD, the club stations are dominating the QSO count, so reducing these 1D/1E brings the distribution into something more reasonable for a FD simulation. Below is the imported call history distribution...
```
ARRL FD - Call History Distribution by Classification (20 calls/dot)
 1A:  270 *************
 2A:  568 ****************************
 3A:  572 ****************************
 4A:  259 ************
 5A:  127 ******
 6A:   54 **
 7A:   22 *
 8A:   13 
 9A:    6 
10A:    2 
11A:    4 
14A:    1 
17A:    2 
 1B:  274 *************
 2B:   44 **
 3B:    2 
 4B:    1 
 1C:  105 *****
 2C:    7 
 4C:    1 
 1D:  612 ******************************
 2D:   32 *
 3D:    7 
 4D:    2 
 6D:    1 
 1E:  214 **********
 2E:   17 
 3E:    6 
 4E:    4 
 5E:    1 
 1F:   39 *
 2F:   92 ****
 3F:   57 **
 4F:   35 *
 5F:    9 
 6F:    4 
 7F:    2 
 8F:    2 
 9F:    2 
```
This is my last planned change for 1.84. I'll post a final release-candidate build for final testing before release.

@scotthibbs

**Comment by w7sst** [comment]
Here is the final [v1.84-rc4 build](https://1drv.ms/u/s!AiN4lELeOz01q34X8LA963GoLo2k?e=Ugj3LE). I have no other planned changes to make. Please give it a spin as you have time and report back with any test results. Thank you. 73, Mike

@scotthibbs

**Comment by scotthibbs** [comment]
Great Job - v1.84-rc is a much better distribution.
