### ISSUE TITLE
Correct the call history file for the JARL ALL JA contest

### ISSUE THREAD

**Issue by jr8ppg** [w7sst/MorseRunner#307]
### Description
JA users have reported that the exchange number in the JARL_ALLJA.TXT file is incorrect.
The exchange number for 8 areas is a 3-digit number starting with 1.

### Steps To Reproduce

1. 
2. 
3. 

### Version information

  - Morse Runner version: [e.g. 1.84]
  - OS/Version: [e.g. Windows 10]
  - JARL_ALLJA.TXT is Last Edit,2024-02-02

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi @jr8ppg ,

I'm hoping to release v1.85 by the end of this month.

Can we mark this Issue as verified?

Do you have any other call history file changes you would like to make?

Thank you,
Mike W7SST

@scotthibbs

**Comment by w7sst** [comment]
@jr8ppg 
I am marking this issue as closed. I hope to release 1.85 before the end of September.

73,
Mike W7SST
