### ISSUE TITLE
Readme Text  correction - Response  

### ISSUE THREAD

**Issue by K5GQ** [w7sst/MorseRunner#323]
Full Exchange - Description
The caller is asking for FULL EXCHANGE; CALL then exchange. 
 F5 then F2. 

Randomly occurs - Steps when it happens 
<Morse Runner has sent the exchange.  The caller repeats,  sending  "AGN" or "NR" -->
1. 
2. 

#### Reproduces how often

All  Versions information

  - OS/Version: [e.g. Windows 10]

### Additional context
In the readme file under Responses 
5.  "R" with their exchange.
          When you get the exchange hit enter to log it.
          Please note that occasionally you will get "NR?" and "AGN" multiple times. Respond with

Change From 
                  F2 until you get that "R" (Roger) and the exchange.
change to
                 F5 then F2.  This is a FULL exchange,  you will get that "R" (Roger) and the exchange.  respond with F3,  "TU".
 
 change

**Comment by w7sst** [comment]
@scotthibbs 
Hi Scott, do you want to f ix this one? It is a change to the `readme.txt` file only.

**Comment by w7sst** [comment]
@K5GQ 
Thank you for submitting this bug and suggested changes to the `Readme.txt` file. Will you please review the changes I made in the pull request/review #346. This link should show you the changes to the text. Please comment in either the review or here if you would like additional changes.

Thank you,
Mike W7SST

@scotthibbs

**Comment by K5GQ** [comment]
Mike,

Sorry for the delay.
confirming change

Yes this does work, If I hear the NR or AGN a second time - F5 + F2; 
then enter the exchange and TU F3

Mark

On 2024-09-03 4:15 am, Mike Brashler wrote:

> @K5GQ [1]
> Thank you for submitting this bug and suggested changes to the 
> Readme.txt file. Will you please review the changes I made in the pull 
> request/review #346 [2]. This link should show you the changes to the 
> text. Please comment in either the review or here if you would like 
> additional changes.
> 
> Thank you,
> Mike W7SST
> 
> @scotthibbs [3]
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/K5GQ
[2] https://github.com/w7sst/MorseRunner/pull/346
[3] https://github.com/scotthibbs
[4] 
https://github.com/w7sst/MorseRunner/issues/323#issuecomment-2326014114
[5]
