### ISSUE TITLE
CQWW - Allow user to send letter (cut number) in sent exchange

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#331]
### Description

The following was reported by Ariel, AE3CX while reviewing the [proposed GUI Improvements](https://github.com/w7sst/MorseRunner/discussions/330) discussion...
>Hi Jim and all,
>
>I´m testing it and like it very much, think you have achieved your goals,
>for now the only thing I have found is that it does not allow me to include
>a letter in the zone when in CQWW ( I usually send 5NN A4).
>
>Very nice layout, thanks
>
>73
>Ariel
>EA3CX

### Steps To Reproduce

1. Select CQWW
2. Enter `5nn A4` in the user's sent Exchange
3. An error is displayed

#### Expected behavior
Should be able to send cut-numbers in user's sent exchange.

#### Actual Behavior
An error is reported.

#### Reproduces how often
100%

### Version information

  - Morse Runner version: 1.85p (prototype), and probably all prior versions

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
@AE3CX @K6OK 
Hi Ariel and Jim,
I am working on a fix for this and had a question...

How common is it for sending stations to use a cut number for the CQ Zone's 10-19 (e.g. A0, A1, A2, ..., A9)? Do contesters also use cut numbers for the '0' and the '9'? Should we treat '10' or '19' any different than '12...18'?

I'm trying to get some feedback for what frequency I should use the cut number for the DX Stations? What do you notice when running the CQWW Contest?

CC: @f6fvy, @jr8ppg @scotthibbs

**Comment by K6OK** [comment]
Hi Mike -- I checked my CQWW logs and I found no cut numbers but I do remember hearing them frequently. I use call history with N1MM and it populates 14 in the zone field as I'm typing the call, then I listen for 14 or A4 to verify, then hit Enter to log it.  Thus the cut number never gets recorded.

My impression is 40% use of leading A is on the low side for the popular zones 14, 15 and 16.  Brazil sends a lot of AA.   I don't recall but it's probably safe to assume zones 10, 20 and 30 will use following T's.  Some NA will send leading T for zones 3,4,5.  I don't, 5NN 3 works for me.  Sorry I don't have good data to give you, only my vague impressions. -- Jim K6OK

**Comment by f6fvy** [comment]
I rarely heard z9 stations sending '9'. The vast majority of them send N like I do as FY5KE : 5NN N

**Comment by w7sst** [comment]
Thank you for the feedback. I will switch over to 90% using the cut number for the zone.

**Comment by w7sst** [comment]
I went with 97% of the time.

I also notice that N1MM does not allow typing 'A', 'T', 'O', or 'N' in the CQWW Contest. It seems that they allow this for other contests.

I'm wondering what MRCE should do for these cut numbers for the CQ-Zone? I would like to stay consistent with N1MM for practicing purposes, but miss it in MRCE.

Thoughts?

@K6OK @f6fvy

**Comment by w7sst** [comment]
> I also notice that N1MM does not allow typing 'A', 'T', 'O', or 'N' in the CQWW Contest. It seems that they allow this for other contests.

After thinking about this more, I think we should allow user to type 'A', 'T', 'O', or 'N' and have it translated to the equivalent number. The numeric value will show up in the log report. I think this is consistent with prior behavior and will work for now.

Mike W7SST
