### ISSUE TITLE
Remove "..." in Log Report column headers

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#344]
### Description
The Log Report is showing "..." in the column headers because the initial column widths are too narrow.

This image is from Jim...
![dots-in-column-headers](https://github.com/user-attachments/assets/882d3406-ae2e-4719-9ae3-943a5b3af4c3)

### Steps To Reproduce

1. Select the ARRL Sweepstakes Contest.
2. Start the contest.
3. Finish one or more QSOs.

#### Expected behavior
Column headings should display text only without any "...".

#### Actual Behavior
The column headers and some data is showing "...". See above screenshot.

#### Reproduces how often
100%

### Version information
  - Morse Runner version: v1.85-dev.4 (development release $)
  - OS/Version: [e.g. Windows 10]

### Additional context
- This problem was originally reported in this [pull request](https://github.com/w7sst/MorseRunner/pull/343) for Issue #55.
- this was first noticed with the ARRL Sweepstakes Contest. This version included changes to how column widths were initialized. Something in this earlier change is causing this problem.
- Jim is running a standard 1920x1080 monitor at the default 100% scale.

### Tasks
- [ ] Coding
- [ ] Integration and code review
- [ ] Verification

**Comment by w7sst** [comment]
From Jim (see #343)...
> Mike -- This is from my desktop. 1920x1080 at the default 100% scale.
> Edit: Github is upsizing the image. Click on it and it shows up on my browser as a new tab correctly sized.
![image](https://github.com/user-attachments/assets/852f1ac0-b250-47a6-a611-5606f41f8c33)

**Comment by w7sst** [comment]
Jim, I posted a new build [here](https://1drv.ms/u/c/353d3bde42947823/ER-7ISIdjyZGl_uLTW0bjLsBhNgK53Uy9fejdNwLlrsYIQ?e=GbgEtj). 

1. Please let me know how the column widths appear on your screen.
2. Also, please start the NCJ NAQP and run a few QSOs to make sure the Log Report is not showing any dots.

Thank you,
Mike W7SST

@K6OK @scotthibbs

**Comment by K6OK** [comment]
Mike -- tested both contests on my desktop (100% scaling) and laptop (125% scaling).  No dots seen, looks good.
Jim K6OK

    On Monday, September 2, 2024 at 05:02:44 PM PDT, Mike Brashler ***@***.***> wrote:  
 
 


Jim, I posted a new build here.
   
   - Please let me know how the column widths appear on your screen.
   - Also, please start the NCJ NAQP and run a few QSOs to make sure the Log Report is not showing any dots.

Thank you,
Mike W7SST

@K6OK @scotthibbs
