### ISSUE TITLE
Invalid Callsign is displayed in red under the QSO list

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#360]
### Description
Laurent reported...
> One remark : When "invalid callsign" is displayed in red under the QSO list (for some reason), it never disappears. At least, entering other QSOs afterwards doesn't make it disappear. Not a big deal, but I wanted to let you know.

### Steps To Reproduce
- Start contest simulation
- Hit F1 to get callers
- Hit the "+" key with no entry
- "Invalid callsign" is displayed
- Entering now correct callsigns and exchanges doesn't make it disappear

_Originally posted by @f6fvy in https://github.com/w7sst/MorseRunner/issues/350#issuecomment-2365231457_

**Comment by w7sst** [comment]
Fixed in v1.85-rc4.

Laurent, can you validate this with the latest build?

Thank you.

@f6fvy @scotthibbs

**Comment by f6fvy** [comment]
It works fine now with the latest build. Thanks !
