### ISSUE TITLE
Do not get an R from dx station after correcting a bad call

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#370]
### Description

As reported by Bob, @WR7Q

> Hi Mike,
> 
> I am using Windows 11 and CQ WPX.
> 
> I have been playing with this a bit and found the following:
> 
> When I put in the incorrect callsign and it sends it again, then I put the correct one in, I just get his exchange. I do not get an 'R' which is necessary to receive before I go on.
> 
> 73,
> Bob WR7Q
> CWA Admin

### Steps To Reproduce

1. 
2. 
3. 

### Version information

  - Morse Runner version: 1.85
  - OS/Version: Windows 11

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ ] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi Bob,
I have tried to reproduce this, but I am missing some information from you. Are you using function keys to send your actions, or the `ENTER` key? Can you provide extra details on how you are sending each message.

Thank you,
Mike

**Comment by WR7Q** [comment]
I send the callsign with the enter key only.

73 Bob WR7Q

**Comment by w7sst** [comment]
Hi Bob,
One more question... Are you able to reproduce this problem on the prior release 1.84? Or on the original 1.68?

Thank you,
Mike

**Comment by WR7Q** [comment]
I'll try tomorrow.

73 Bob WR7Q

**Comment by WR7Q** [comment]
Hi Mike,

1.84 and 1.68 work just fine.

73,
Bob WR7Q
CWA Admin

**Comment by w7sst** [comment]
Hi Bob @WR7Q ,

I have been trying to reproduce and I don't think I am able to reliably reproduce the problem. My testing is showing the same behavior on both 1.84 and 1.85. I know some logic has changed in 1.85, especially in the fixes for the ghosting issue.

To help reproduce this issue, can you help provide...

1. Are you running in Single Call mode or in Pile-Up mode? I have been running Single Call mode.

2. What have you entered in the various exchange fields before you send? When you send your information, what are you using (either function keys or Enter). You have already told me you are sending the callsign with the `Enter` key, but I also need to know the contents of the Number field (i.e. have you entered their serial numbers).

3. Next, what does the DX Station send back to you after you send the corrected callsign. I think you have said they send the callsign only. 


Please let me know these details for both 1.84 and 1.85. The bug is deep inside the state machine of the DX Station and the state of each field is used in determining the next state of the state machine and thus what the DX Station will send next.

I have studied and compared the code between 1.84 and 1.85 and cannot see any obvious changes. I have instrumented my code to help the debugging process, but I am lacking the extra detail of what is being sent by you (the field contents), how you send it (which key or `Enter`) and finally what the DX Station is sending back. This extra information will really help.

Thank you for your help.
Mike

Adding @scotthibbs

**Comment by WR7Q** [comment]
I'll get it for you in the morning. I am doing single call. You have to put
the wrong call first, then he sends again. When you put the correct call,
he does not give an 'R'.

**Comment by w7sst** [comment]
okay. I'm guessing that you have only entered the callsign, and not their serial number exchange.

**Comment by WR7Q** [comment]
Yes that is correct.

**Comment by WR7Q** [comment]
Hi Mike,

I tested this again just now.

1.84 works correctly.

1.85 never returns an 'R' after you enter an incorrect call sign after
which he resends his call sign and then you enter the correct call sign and
hit enter. He just sends his exchange.

73,
Bob WR7Q
CWA Admin

**Comment by w7sst** [comment]
Hi Bob,
I was able to reproduce the issue you are reporting. Thank you for the extra information.

I have also found the problem in the code and will get a fix ready. We can consider a 1.85.1 bug-fix release in another month or so. We would want to see if any other bugs are reported.

73, Mike

**Comment by WR7Q** [comment]
Ok good to know. Thanks.

73 Bob WR7Q

**Comment by w7sst** [comment]
Hi Bob,

[Here is a build](https://1drv.ms/u/c/353d3bde42947823/EYpdLVcuiw5FgtYcYyHXNqEBF9t7A0M7eWOmZWbUUOtGwQ?e=we7cFg) containing a fix to this issue. Do you have time to give it a spin and verify the fix for us?

Thank you and 73,
Mike W7SST

**Comment by WR7Q** [comment]
Hi all,

1.85.1 is working correctly. Tnx

73,
Bob WR7Q
CWA Admin
