### ISSUE TITLE
How do we release and install MorseRunner?

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#38]
## Summary
We do not yet have a solution for releasing version 1.80 of Morse Runner. The code is ready, but how do we install it.

## Motivation
duh...

## Detailed Description
- Need to find a site to host the release image.
- generate an install script
- update release notes

**Comment by scotthibbs** [comment]
I'm not opposed to finding another site to post our releases. Especially since this can also be used later to post scores. One of the great things I like about this program was the ability to brag about breaking my own record. I have ideas that will help eliminate bogus or spam scores that ended submissions at https://www.bh1scw.com/mr/score. 

However at this early stage, it might be beneficial to use the github release feature just to bring awareness to our project here and get help.

I'll be glad to help write the release notes. As for the install script, is this directions on install or coding? All the versions I used were not installed, just an exe and supporting documents in the zip (for our page like bh1scw or github). Please let me what I need to do. 
Scott

**Comment by w7sst** [comment]
The install script is for end-user installation. I agree with using the github release feature to help bring awareness to this project - good idea.

Since each contest has a corresponding call history file, we are starting to get several files involved. A zip image will work, but the user has to install it somewhere. This is fine, as long as we document how to do this. We could also look into creating a simple install image what will install the software into appropriate Windows directories. For now, keeping it simple as a zip file will work fine (which is what you were suggesting). Perhaps some of the other MR authors (which we still have to invite into the project) will have some ideas for the future.

For now, let's initially pursue the idea of using a zip file for installation.

Scott, can you do some reading and learn a little more of how the release process works from within GitHub? Perhaps add some notes here along with some links to pages showing us what we need to do. I expect that one of us will need to compile the MR.exe file and then create the zip file and upload it. I know GitHub supports user Actions, but I have not learned how any of this works. So maybe to start, please learn what you can on how the GitHub release system works and propose on how we might use it. Eventually we will need developer instructions for creating a release and end-user instructions for installing a release.

Thank you.
73, Mike

**Comment by w7sst** [comment]
There are many pages describing how to generate a release. Here is another one: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by w7sst** [comment]
@scotthibbs , I did learn how to create a release. It is a pretty simple process. I will create a zip file and wait for the Readme.txt file to be completed. Once we have everything, I can create the 1.80 release.
thanks, Mike.

**Comment by w7sst** [comment]
@scotthibbs , I'm going to assign this Issue to you for further study.

I'm proposing that you take over the release process and Release Notes as you have offered. I can generate the binary zip file and include it into your Release Draft before you finalize the release.

1. Start with this description on the release process: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

It describes how Release Notes can be automatically generated by GitHub. It appears Issue titles assigned to this release are included in the release notes. I would imagine this produces a draft which can could be further edited before the release is published. I would suggest you experiment with this to see if it would help us with future Release Notes.

2. Starting at the repository home page, click "[Create a new release](https://github.com/w7sst/MorseRunner/releases/new)" in the Releases section on the right.
- **before you start, create a dummy branch off of main**. You can do this by creating a "Pull Request" for this issue. Creating the pull request allows you to create a branch associated with this issue. I can help you if you don't see how to do this. We will not merge this branch to main.
- you can then create and fix a few pretend bugs using this dummy branch. this will create an issue or two that you can pull into your pretend release notes.
- go through the Create Release process and create a release from your special branch.
- Try using the Generate Release notes feature and learn how the information from the Issues are pulled in and how they need to be managed.
- we want to learn if this automatic generation process is worth using.

3. You can create as many pretend releases as you want while you are learning how this works.
- let me know if I can help.

4. When complete...
- document what you learn here in this issue. A set of instructions of how to create a release.
- delete any pretend releases when you are done with them. Please use a pretend version number.

5. Assuming we learn how the automatic Release Notes generation works, we also have the `Readme.txt` file that is included in the zip file. This creates a problem in that GitHub-based release notes are auto-generated, but the `Readme.txt` file is currently manually edited. I suppose we can start by auto-generating the Release Notes and then copy this information into `Readme.txt` prior to creating the zip file.

What do you think of this idea?

**Comment by scotthibbs** [comment]
Ok.. The programming side of things here on GitHub seems Greek to me such as creating branches and issues and having them merged or not merged into the main.  

I'm thinking it is best we do as you have done, and create a draft with the files as you want released. Just like the process we have done and are doing, once you decide a release is needed, we can write the readme for it (like we edited) and when complete, create the release for me to write release notes.  Ultimately my job here is cheerleading and doing the things here on GitHub that distracts from programming. 

The generate automatic release notes created the following below your previously written notes. I've edited our release notes for this release and copied them here for you to see:

"""""""""""""""
What's Changed
Merge draft copies of README.md and CONTRIBUTING.md files by @w7sst in https://github.com/w7sst/MorseRunner/pull/5
Update issue templates by @w7sst in https://github.com/w7sst/MorseRunner/pull/7
added BH1SCW 1.72 version by @scotthibbs in https://github.com/w7sst/MorseRunner/pull/8
W7sst issue templates by @w7sst in https://github.com/w7sst/MorseRunner/pull/9
Fix https://github.com/w7sst/MorseRunner/issues/10 - bad URL links in CONTRIBUTING.md by @w7sst in https://github.com/w7sst/MorseRunner/pull/11
Issue https://github.com/w7sst/MorseRunner/issues/18 - bug fix - CWOPTS.isnum() incorrectly considered an empty string as valid by @w7sst in https://github.com/w7sst/MorseRunner/pull/19
Issue https://github.com/w7sst/MorseRunner/issues/16 - bug fix - last char of last field is dropped by TCWOPS.De… by @w7sst in https://github.com/w7sst/MorseRunner/pull/17
Issue https://github.com/w7sst/MorseRunner/issues/14 - Add some comments to CWT code in SaveQso(). by @w7sst in https://github.com/w7sst/MorseRunner/pull/15
Issue https://github.com/w7sst/MorseRunner/issues/21 - rework ct7aup's Rx CW Speed adjustment by @w7sst in https://github.com/w7sst/MorseRunner/pull/22
Resolves https://github.com/w7sst/MorseRunner/issues/23 - rework - move digit and CW Rx settings I/O into Ini.pas; code simplification by @w7sst in https://github.com/w7sst/MorseRunner/pull/26
Fixes https://github.com/w7sst/MorseRunner/issues/27 - restore whitespace differences by @w7sst in https://github.com/w7sst/MorseRunner/pull/28
Integrate Ve3nea-normalized branch into our main branch by @w7sst in https://github.com/w7sst/MorseRunner/pull/30
Merge fixes for Issue https://github.com/w7sst/MorseRunner/issues/31, https://github.com/w7sst/MorseRunner/issues/32, https://github.com/w7sst/MorseRunner/issues/33, https://github.com/w7sst/MorseRunner/issues/34 into main branch by @w7sst in https://github.com/w7sst/MorseRunner/pull/35
Merge FD Prototype by @w7sst in https://github.com/w7sst/MorseRunner/pull/37
initial changes for 1.80 release notes/Readme.txt file by @w7sst in https://github.com/w7sst/MorseRunner/pull/40
New Contributors
@w7sst made their first contribution in https://github.com/w7sst/MorseRunner/pull/5
@scotthibbs made their first contribution in https://github.com/w7sst/MorseRunner/pull/8
Full Changelog: https://github.com/w7sst/MorseRunner/commits/v1.80
"""""""""""""""""""

I'm thinking this is completely helpful for current contributors and future contributors wanting to catch up. It seems ugly to my eye but I can see how helpful it is as a development roadmap.  

I want to turn on GitHub Discussions for this project. I started to do it but wanted to know if you had any objections. I want to do this before we do this release. GitHub will create a discussion for this release to get feedback from regular users that may not need an issue created (such as positive feedback). 

Thanks,
Scott

**Comment by scotthibbs** [comment]
If you are ok with GitHub Discussions, I'll turn that on and then issue our 1.80 release with the discussion added. 

Also, we already have an issue #44 for this release. This will always happen. I'm thinking I should add that to the release notes and point out that we encourage feedback and issues if any are found. 

Scott

**Comment by w7sst** [comment]
Hi Scott,
Yes, I am ok with GitHub discussions. I have been reading about them the past few days and was thinking of asking you the same thing. So yes, please turn them on. Let me know if you want me to add/do anything.

Let's not worry about documenting currently known problems (e.g. #44). You are correct, there will always be bugs that have not been fixed. For this project, I don't think it is necessary to document all of them. There will be the occasional bug/issue that we will want users to be aware of - in that case, we can document it. Otherwise, users can look at the issues list in GitHub if they are interested. We are duplicating information if we always copy them into the Release Notes.

In a future release note (or now if we have time), we can encourage people to report feedback/questions/bugs directly to GitHub/issues as you suggest above.

**Comment by w7sst** [comment]
I will work towards finishing the release process for our 1.80 release. As I go through that process, I'll better understand GitHub's automatic Generate Release Notes. It sounds like you have already tried this. I did like how the developer and issue numbers are included in each line. I agree that it starts getting a little messy/ugly, so it is best included at the end of the Release Notes. We will get it figured out after a release or two. Each time we do a release, we can document the process and improve the content with each release.

Thank you again for your help.

73,
Mike

**Comment by w7sst** [comment]
Scott, I removed from the new "What's Changed" section any integrations leading towards the Community portion of this first release (the README.md, issue templates, etc.). You can view my changes [here](https://github.com/w7sst/MorseRunner/releases).

Let me know when you have enabled the Discussions and I'll publish this release. Thank you for your help.

**Comment by scotthibbs** [comment]
Mike, 
I can't enable/setup the discussions (I get a 404 page error which is generated due to not having authentication). 

I'm ok with the edits you made. If you set up Discussions before the release, there is an option in the release to start a discussion topic on this release when it is published. 

Let me know if you need me to do anything further.
Scott

**Comment by w7sst** [comment]
Discussions are enabled.

**Comment by scotthibbs** [comment]
I've added a line to invite discussions.. Think it's ready to publish.
