### ISSUE TITLE
MR Splash Screen update

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#56]
### Description

Since Alex Shovkoplyas didn't release 1.8, and we would like the current year displayed, maybe we should change the splash screen to look more like our readme or something similar.
   
				Morse Runner
				Contest Simulator
				freeware

               Version 1.80 Field Day Contest Prototype

           Copyright (C) 2004-2016 Alex Shovkoplyas, VE3NEA
                  http://www.dxatlas.com/MorseRunner/

    Copyright (C) 2022 Morse Runner Community Edition Contributors
               https://www.github.com/w7sst/MorseRunner/

### Steps To Reproduce

1. Open MorseRunner.exe
2. Splash screen before starting.

#### Expected behavior
Updated splash screen

#### Reproduces how often
100%

### Version information

  - Morse Runner version: 1.8
  - OS/Version: Windows 10

### Additional context

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [ x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
Hi @scotthibbs ,
I've been working on the splash screen. I've added the copyright messages and "CW CONTEST SIMULATOR".

I've also included the `Help | About` dialog.

I wanted to show you and get your thoughts.

![image](https://user-images.githubusercontent.com/106113737/195968006-d3f4e75f-48c8-4df7-ab05-18558641a820.png)

**Comment by scotthibbs** [comment]
I like it. I like it a lot. It's a winner!

**Comment by w7sst** [comment]
Okay then. I’ll get both the about box and splash screen bugs checked in
soon.
