### ISSUE TITLE
Menu Item: Help/Web Page

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#59]
### Description

The "help"/"web page" should be redirected to our GitHub page instead of the old 1.68 version at dxatlas.com. 

### Steps To Reproduce

1.  Go to the Help Menu
2. Click on Web Page
3. See Alex's 1.68 version download page. 
4.  We can create a help page (discussion topic) or a help file.

#### Expected behavior

Help for the current version of MR

#### Reproduces how often

User is taken to an older version's webpage. 

### Version information

  - Morse Runner version: 1.8
  - OS/Version: Windows 10

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.
- I could also help with the help file or document or webpage.

**Comment by w7sst** [comment]
At a minimum we can redirect our GitHub page as you have mentioned elsewhere. @scotthibbs

**Comment by w7sst** [comment]
This Issue could be broken into two issues:
1. replace current web page with one of our web pages (this Issue)
2. implement a help file (new Issue). This is a longer-term project. As you have suggested, the help file needs to be written. Or, we can continue using the Readme.txt file to serve as a help file. Maybe we will find a volunteer to help write a help file in the next 3 to 6 months.

Based on the above, I would recommend adding a new issue for the Help file. @scotthibbs

**Comment by w7sst** [comment]
@scotthibbs ,
So what webpage do we want `Help > Webpage...` to direct them to?

Options
1. https://www.github.com/w7sst/MorseRunner#readme
2. https://www.github.com/w7sst/MorseRunner
3. https://github.com/w7sst/MorseRunner/discussions/categories/morse-runner-1-80 (which is currently empty)

thoughts?

**Comment by scotthibbs** [comment]
For now the readme gives the most help so I think that is best. 

I'll create an issue for the help file to be written. I can start on that too unless someone wants to do it.

**Comment by w7sst** [comment]
> I'll create an issue for the help file to be written. I can start on that too unless someone wants to do it.

Yeah, let's see if some wants to pick it up. I think that for now, the current `Readme.txt` is sufficient as a help file.

**Comment by w7sst** [comment]
Here's a thought... What do you think of renaming the `Help | Web Page...` menu pick to `Community Web Page`?

![image](https://user-images.githubusercontent.com/106113737/195741801-fb906c12-295a-466c-beed-894e124f30c3.png)

In some ways, I like using "Community Web Page" over "Web Page" because it was not obvious what "Web Page..." would do for me or where I would go if I clicked it.

An alternate name might be `Help | Community Home Page` or `Community Edition Home Page`.

Also note that I'm removing the ellipsis (...) from the three menu picks since these three menu items do not open dialogs that require additional information (like `File | Open...`).

Thoughts?

@scotthibbs @ct7aup @BH1SCW @DF9TS @jr8ppg

**Comment by scotthibbs** [comment]
I like Community Edition Home Page best. Good Idea.

**Comment by w7sst** [comment]
Change #71 - rename Help menu's 'Web Page...' to 'Community Edition Home Page'

This change was integrated without updating the pull request's message with automatic linking to this issue. So I'm manually adding the message now.

**Comment by w7sst** [comment]
Help menu now shows `Community Edition Home Page`

![image](https://user-images.githubusercontent.com/106113737/195783151-05309ce4-a18a-4930-bc29-b1416a637a8e.png)
