### ISSUE TITLE
Title Bar needs renamed

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#61]
### Description

Title Bar for version 1.8 reads "Morse Runner - ARRL Field Day" which is correct but this should read "Morse Runner - Community Edition" for better recognition of the program. 

### Steps To Reproduce

1.  Open the program
2. Read the program title bar at the top next to the icon. 
3. 

#### Expected behavior

I'm thinking this could be generic such as "Morse Runner - Community Edition" so it doesn't have to be changed at every version. However adding the version number here would be more precise and easily seen "Morse Runner 1.8 - Community Edition". If we can remember to change it at every release. 

#### Actual Behavior

Title gives a contest name instead of the program name. 

#### Reproduces how often
100% 

### Version information

  - Morse Runner version: 1.8
  - OS/Version: Windows 10

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
@scotthibbs 

Hi Scott,
If I understand correctly, you are suggesting to drop the current contest name from the title and use `Morse Runner - Community Edition`.

I was heading in the direction of appending the current contest name in the title as this is common for applications to show the app name and current document in the app's title bar. However, I think you have changed my mind. I realize now that adding the "Contest Name" to the title is redundant with the Contest Selection in the upper right corner.

I'm also thinking that adding the version number doesn't add value to the title bar. I'm thinking that `Morse Runner - Community Edition` is sufficient and adding the version number seems to make it harder to read: `Morse Runner 1.81 - Community Edition`. 

Below shows `Morse Runner - Community Edition` in the title bar.

![image](https://user-images.githubusercontent.com/106113737/195681699-f7046672-1d89-452b-9da3-3f1616e37804.png)

We can keep the version number in the About Box. We will address this in the About Box Issue #60 .

thoughts?

**Comment by w7sst** [comment]
@scotthibbs 

Hi Scott,
If I understand correctly, you are suggesting to drop the current contest name from the title and use `Morse Runner - Community Edition`. I like this.

You changed my mind... I was heading in the direction of appending the current contest name in the title as this is common for applications to show the app name and current document in the app's title bar. I realize now that adding the "Contest Name" to the title is redundant with the Contest Selection in the upper right corner and doesn't add value.

I'm also thinking that adding the version number may not add value to the title bar. Simply using `Morse Runner - Community Edition` is sufficient and adding the version number is making it harder to read: `Morse Runner 1.81 - Community Edition`. I think keeping it simple is the best course to take here.

Below shows `Morse Runner - Community Edition` in the title bar...

![image](https://user-images.githubusercontent.com/106113737/195684118-5d8d6647-377a-4e7f-bda6-65b86cc20b4c.png)

We can keep the version number in the splash screen and the About Box. We will address the About Box wording in Issue #60 .

Thoughts?

**Comment by scotthibbs** [comment]
That's absolutely perfect. "Morse Runner - Community Edition" in the title bar. :)
