### ISSUE TITLE
NAQP Sends Wrong Exchange to Caller

### ISSUE THREAD

**Issue by K6OK** [w7sst/MorseRunner#85]
### Description

In one contest, does not send correct exchange to the caller.

### Steps To Reproduce

1. Select Field Day, enter exchange, run simulation.
2. Select NCJ NAQP, enter name and state.
3. Run simulation.  The exchange sends part of Field Day exchange to caller instead of Name.

### Version information

  - Morse Runner version: [e.g. 1.81]
  - OS/Version: [e.g. Windows 10]

### Can you help?
[x] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
I have confirmed this issue and will work on a solution soon. you are helping us test early prototype code, so we appreciate your testing and feedback.

**Comment by w7sst** [comment]
Hi @Yagi-Berra ,
I have posted a preliminary v1.82 release at https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq. This zip file contains the latest code, including a fix to this bug you reported earlier. If you have time, please install and verify this bug.

Thank you,
Mike

**Comment by w7sst** [comment]
Verified by @K6OK in a separate posting. Thank you!
