### ISSUE TITLE
Run button renamed to Stop when running.

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#96]
Was able to walk through the setup of this program from a new user. One of the several things that seemed confusing was the two areas to select contests or run modes. I believe a redesign of the run button needs to be done. 

I think it would make sense to combine the dropdowns for the run button into the Contest mode or add a second dropdown next to the contest mode so that these "modes" can be more clearer to a new user. This would make the run button a simple run/stop button. 

It was also confusing for him on how to stop a contest once it was started. The run button still says run instead of changing to Stop or End. 

I thought this was a good suggestion.

**Comment by scotthibbs** [comment]
There seems to be concensus to change the button label to "Stop" while MR is running. So this issue needs to be confined to this change only. 

(Changing the drop down and contests modes will be separate individual issues once this one is completed. This would include having a setting to use the 1.68 original contest modes and a new feature like a pause button.)

**Comment by scotthibbs** [comment]
This issue will be in the 1.83 release.

**Comment by w7sst** [comment]
@scotthibbs ,
Hi Scott,
When I was working on this Run/Stop button work, I knew I had seen a prior Issue created, but couldn't find it. I was in a hurry, so I created a new Issue. I should have asked you where this one was. Thanks for closing this out. We will still continue discussions on the UI and what to do with the Start/Stop/Pause operations, along with duration, run mode, etc. K6OK has some ideas and a proposed UI that he worked on last year.
