### ISSUE TITLE
"First Time?" menu item

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#98]
I need to write a "First Time?" menu button for the menu bar. 

The first item should be "First Time Setup" and should include a quick setup on how the program is setup and used. 

Under this should be the name of all our contests in order of the contest dropdown, and if clicked, provide help with each contest and should include blurbs on the contests and exchanges with info on the real dates and links to these contests.

I've assigned myself the texts to write and once done, we can program the menu buttons to be populated.

**Comment by scotthibbs** [comment]
Silly me.. I added this to the already existing "Help File needs to be written #67"

**Comment by w7sst** [comment]
> Silly me.. I added this to the already existing "Help File needs to be written #67"

Scott, you might copy your "first time user" text here and then mark this Issue as a `good first issue`. I'll add notes on how to use a MessageBox to display your text.

**Comment by scotthibbs** [comment]
Reopening.. This issue is for creating a menu item to open a MessageBox to display the following:

First Time?
Welcome! This is the first time setup:

Select the Contest you wish to operate.
Type the exchange you wish to send.
In the station section replace VE3NEA with your call.
Select your CW Speed, Tone, and the min/max speed settings.
Under band conditions you can select any realistic hardships.
Activity is the average amount of responses you want per CQ.
So if no one responds, you might get twice the number the following time.
This is a pile up trainer after all. - have fun.
Select the time limit you want to run the contest.
The Run button has a drop down.
Single Call - immediately you will get someone trying to contact you.
Pile up - You need to call CQ to start. hit enter or F1

Don't forget to provide feedback at [www.hithub.com/w7sst/MorseRunner/](http://www.hithub.com/w7sst/MorseRunner/)

**Comment by w7sst** [comment]
As a coding suggestion for this Issue...
- You can duplicate the implementation for `Help | About`.
- Add a menu item and associated event handler function.
- Place the text above into the MessageBox call.

Please include a screen shot with the pull request/code review.

**Comment by w7sst** [comment]
Hi @scotthibbs ,
We may have to defer this for 1.82 since no one has volunteered for it. If you feel strongly we should include this for 1.82, I can work on it over the next week - it shouldn't take long. Otherwise, I think we are getting close to releasing 1.82. An early compile of 1.82 is available [here](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq).
